### ISSUE TITLE
链接错误

### ISSUE THREAD

**Issue by xlx0010** [Embedding/Chinese-Word-Vectors#1]
请问有公布训练好的词向量的文件吗？
为什么点击词向量的链接然后跳转到了百度首页？谢谢！

**Comment by shenshen-hungry** [comment]
@xlx0010 这个项目一部分是ACL 2018论文的内容，会议还未召开，所以有些内容还没有完全放上来。项目很快就会完善的，词向量也会提供下载链接。我们希望这个项目可以帮更多的人更好使用词向量。你可以随时关注项目动态，谢谢你的支持和理解。

**Comment by xlx0010** [comment]
哦好的，谢谢！
