### ISSUE TITLE
请问作者用linux系统读取过这些文件吗？

### ISSUE THREAD

**Issue by mfxss** [Embedding/Chinese-Word-Vectors#10]
从windows上读取正常，上传到linux会出错，这是怎么回事，我具体的看了一下，有几十行被打乱了。

**Comment by shenshen-hungry** [comment]
我们在Windows和Linux上面都试过，没有这种问题。你可以试试在Windows上面直接下载文件，之后不修改，直接传到Linux上面打开。可能是修改了或者是别的原因导致的。

**Comment by mfxss** [comment]
是不是里面有乱码呢？我把压缩包上传到linux，用`tar -xjf sgns.wiki.char.bz2`解压，会出现
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘8 0.365625 -’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors

**Comment by shenshen-hungry** [comment]
你用bzip2来解压bz2的文件。
