### ISSUE TITLE
能不能换个网盘呢？

### ISSUE THREAD

**Issue by LuMelon** [Embedding/Chinese-Word-Vectors#102]
百度网盘的体验太差了，能否传导讯飞云或者其它站点上面呢。

**Comment by shenshen-hungry** [comment]
免费并且容量大的就是百度网盘了，如果速度太慢可以开个会员，毕竟人家不是做慈善的。

**Comment by tommy0607** [comment]
> 免费并且容量大的就是百度网盘了，如果速度太慢可以开个会员，毕竟人家不是做慈善的。

速度慢点没事，但它这样慢到极点直接让所有用户都被迫充会员或用破解
