### ISSUE TITLE
readme 为嘛不用中文？

### ISSUE THREAD

**Issue by leixinhui** [Embedding/Chinese-Word-Vectors#104]
中国人做的中文词向量训练项目，为嘛不能用中文写readme？

**Comment by cmdares** [comment]
>中国人做的中文词向量训练项目，为嘛不能用中文写readme？
@leixinhui 说的太对了！
抓紧修复readme问题，迫切！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shenshen-hungry** [comment]
目前只提供英文readme的原因如下：

1. 英文具有通用性，GitHub是一个英文网站，同时主流学术会议和期刊均为英文，包括本项目相关论文也都是英文撰写和发表，如果不会英语可能无法看懂更多细节。
2. GitHub作为世界性的代码托管平台，面向的对象是世界所有人，因此本着让大量的人使用的原则，英文readme是必须的，而且能上GitHub找项目的中国人大概率会看懂英文，所以中文readme必要性并不充分。
3. 作为一个开源项目，“中国人做的中文词向量训练项目”和“用中文写readme”并不存在直接的因果关系。

欢迎本问题更多讨论，如果确有充分的理由支持中文readme，我们将会更新。

**Comment by SCismycat** [comment]
提这问题真无聊

**Comment by hurui200320** [comment]
学好英语真是比什么都强啊🙂

**Comment by wrptc** [comment]
本着让大量的人使用的原则应该把模型保存google drive上，这样下载会快一些=。=

**Comment by shenshen-hungry** [comment]
@wrptc Google Drive免费空间太少了，只能把使用量最大的词向量上传，实在是没有别的更好的办法。

**Comment by MintLucas** [comment]
尽管英文更具有通用性，但中国人口基数和这是中文词向量，更多的使用者或许是中国人。

层主英文尚可，阅读英文文档时做不到像母语般浏览，同样质量的中文资料和英文资料也一定去选用中文资料阅读参考，因为语言只是交流的工具，任何版本获取速度和质量才是关键，没有必要为了一些逼格去阅读英文。

英文通用是国家发达的产物，作为中国人，我们要有文化自信，争取发表更多的中文文章和中文技术，以后更多的国际期刊能有中国版本，国家大力推的孔子学院在全球生根发芽，各国华人比例也逐渐增高，后百年的通用货币和通用语言未可知。

所以希望可以做个统计，如果中国人用这个更多的话，最好能补充中文readme，无论如何，感谢作者的贡献。

**Comment by plainnany** [comment]
+1 ,最好有个补充中文readme

**Comment by lzh66** [comment]
英文才是国际语言

**Comment by orangetwo** [comment]
很好的问题哈哈哈

**Comment by VisualJoyce** [comment]
可以理解，哈哈

**Comment by cs-liangchen-work** [comment]
哈哈哈，我也好奇，毕竟国人才研究中文的

**Comment by PeterPZhang** [comment]
相对于英文，中国人看中文更习惯一些，而且对于使用者我觉得大部分是中国人吧

**Comment by zhc7** [comment]
人家外国人做的大一点的项目都有简体中文版的readme或者doc，结果中国人做了这么大一个项目居然没有中文版的readme，真的很讽刺

**Comment by VisualJoyce** [comment]
开源就是需要大家众包贡献，非常开心楼上的贡献，问题基本就解决了。

**Comment by VisualJoyce** [comment]
这个词向量一共60GB，如果我个人上传到google drive共享，官方会允许吗？

**Comment by shenshen-hungry** [comment]
终于趁周末有时间完成了中文README，详见：[README_zh.md](https://github.com/Embedding/Chinese-Word-Vectors/blob/master/README_zh.md)。
