### ISSUE TITLE
微博的原语料下载链接失效，能否告知微博数据的时间范围？

### ISSUE THREAD

**Issue by omfoggynight** [Embedding/Chinese-Word-Vectors#107]
请问当时做的时候，微博语料的时间范围是什么时候到什么时候呢？大约多少条微博语料？能否下载到原来的微博语料？

科研工作中要用到word2vec model，需要写明，谢谢！

**Comment by shenshen-hungry** [comment]
刚看了一下，网站更新了链接。
http://www.nlpir.org/wordpress/download/weibo.7z
