### ISSUE TITLE
关于Financial News 金融新闻的词向量的异常word

### ISSUE THREAD

**Issue by SaintLogos1234** [Embedding/Chinese-Word-Vectors#108]
我使用关于Financial News 金融新闻的词向量，我获取词表之后，按照词表的长度顺序排了个序，我发现排名最长的100个word有很多异常的word，如下图所示：
![image](https://user-images.githubusercontent.com/19261529/76403323-b41e2800-63bf-11ea-9f76-60410f8ada8f.png)
包含大量异常的数字和一些标点，这是怎么一回事？

**Comment by shenshen-hungry** [comment]
你发现了一个正常现象。
默认的词表是按照频率排的，也就是高频词排在前面，低频词排在后面。高频的通常都是正常的词，低频的通常都不是词。对于一个文本分词来说，如你这个图里面的情况，这些数字可能来源于财报类的新闻，因此分词的时候把这些划成了一个整体，毕竟分词器是按照通常的文本来设计的。当然即使定制化可能也很难解决这个问题。
因此，使用词向量的时候最好用高频的到低频的排序，对于末尾的词可以适当删减。同时，一般的词向量的使用是先对下游任务进行分词，用分完的的词在词向量词表里面进行查找并取出对应的词向量，而不是直接使用整个词向量文件的所有词。

**Comment by SaintLogos1234** [comment]
好的，谢谢你的回复
