### ISSUE TITLE
训练集Corpus Size是什么单位

### ISSUE THREAD

**Issue by AquaskyCamus** [Embedding/Chinese-Word-Vectors#11]
请问楼主，百度百科corpus  size 4.1G，具体是什么的size？

**Comment by shenshen-hungry** [comment]
处理完并分词的语料大小。也就是词向量模型看到的语料大小。

**Comment by AquaskyCamus** [comment]
就是txt文件的实际尺寸吗？

**Comment by crapthings** [comment]
@shenshen-hungry 多大算大多大算小呢，就是大家一般语料集文件大小都是多少？

**Comment by shenshen-hungry** [comment]
@crapthings 几个G的语料其实在很多情况下就能有很好的表现了。当然，整体情况还是越大越好的，当然收益实际上是非线性的增长，特别大之后效果提升就不显著了。不过对于下游任务来说，用领域相关的词向量会有事半功倍的效果。
