### ISSUE TITLE
How the training sentence was segmented?

### ISSUE THREAD

**Issue by a7744hsc** [Embedding/Chinese-Word-Vectors#112]
To use the embedding, I prefer to use the same segment method with training since this could help reduce OOV words. 

By the way, it would be great if you can provide a small simple for some large file. This gives me a chance to check the format and tokens before a long downloading.

**Comment by shenshen-hungry** [comment]
Please refer to [https://github.com/Embedding/Chinese-Word-Vectors#corpus](https://github.com/Embedding/Chinese-Word-Vectors#corpus)
