### ISSUE TITLE
Baidu Pan links do not work.

### ISSUE THREAD

**Issue by ktxlh** [Embedding/Chinese-Word-Vectors#123]
I tried to click the links, which should lead to some Baidu Pan files, but none of them worked. A 404 not found page was shown (https://pan.baidu.com/error/404.html).
![image](https://user-images.githubusercontent.com/32475254/95476099-787d2800-09b9-11eb-9a31-d0dd3238204e.png)

#86 is a nice alternative, but I believe you may want to fix this.

**Comment by shenshen-hungry** [comment]
Since some IPs are banned by Baidu Pan, you have to change your location via VPN or other tools. Or if you only want to use Mixed Large embeddings, you can download them from Google Drive.

Same question #48

**Comment by ktxlh** [comment]
Oh, I see. Thank you.
