### ISSUE TITLE
PPMI模型维度问题

### ISSUE THREAD

**Issue by ridiculousze** [Embedding/Chinese-Word-Vectors#128]
PPMI模型加载出来之后稀疏矩阵维度不一致，行是635969，而列是635970，想了解：行列的序号是对应的吗，还是列序号未经过排序~如果未排序，可以有列序号对应的词表吗？谢谢！

**Comment by shenshen-hungry** [comment]
ppmi的target word和context word的数量确实是不一样的。因为我们训练用的ngram2vec是先建立target-context pair，这个过程是有subsampling和dynamic window机制，导致了某些词在target和context中出现的次数不一样。
