### ISSUE TITLE
符号"，"似乎缺失

### ISSUE THREAD

**Issue by Zqjjjydl** [Embedding/Chinese-Word-Vectors#129]
采用Word + Character + Ngram方法，以综合语料库作为语料训练出的词向量中，似乎缺少"，"这一字符。我逐行读入并检查了词向量文件，没有找到这一字符及其所对应的词向量，请问这是正常现象吗？

**Comment by shenshen-hungry** [comment]
第一个词不就是“，”吗？也就是文件的第二行。
