### ISSUE TITLE
模型加载失败

### ISSUE THREAD

**Issue by sunnychou0330** [Embedding/Chinese-Word-Vectors#132]
请问一下？可以给出模型加载的demo吗？当前使用命令，对bz2进行了解压，获取到xxx.txt文件，使用如下加载的时候出错，我怎么加载出来，并计算一下两个词的相关性尼？期待回复
import gensim.models
model = gensim.models.Word2Vec.load(r'F:\model\merge_sgns_bigram_char300.txt')

**Comment by shenshen-hungry** [comment]
#8
