### ISSUE TITLE
为什么ppmi.baidubaike.word文件读取的时候，每个维度的值前面都有一个"数值:"且词向量的维度远大于300。

### ISSUE THREAD

**Issue by alanlisten** [Embedding/Chinese-Word-Vectors#15]
例如：
'的 6:0.0506113688733 7:0.233081394134 8:0.435558307'
那些6、7、8是什么，我读取的方式是：
with open('/ppmi.baidubaike.word', encoding='utf-8', errors='ignore') as fr:
wd_vec = fr.readlines()
对wd_vec[56].split()后的维度一般达到1万以上。求解答，难道是我的打开方式不对？

**Comment by shenshen-hungry** [comment]
PPMI的词向量是稀疏编码的，不是稠密的向量，和word2vec那些不同。其中每一行只存非0元素，未显示的元素都是0。在文件最上面给出了词语数量和向量最大长。
具体来说：“的 6:0.0506113688733 7:0.233081394134 8:0.435558307”，意思是位置6的值是0.0506113688733，至于位置6以前的都是0。这样存储方式可以大大减小词向量文件的大小，因为大部分位置都是0。
可以利用scipy之类的python包加载稀疏向量。

**Comment by alanlisten** [comment]
明白了，衷心感谢你们的贡献。
