### ISSUE TITLE
词向量文件中有重复的词

### ISSUE THREAD

**Issue by howardlau1999** [Embedding/Chinese-Word-Vectors#19]
比如人民日报 sgns.renmin.bigram，有 355989 个词向量，但对词汇进行去重之后只剩下 355973 个不同的词语

**Comment by shenshen-hungry** [comment]
查了一下，发现是word开头有全角空格，用strip会删掉，用rstrip处理每行就不会有重复的了。

**Comment by shenshen-hungry** [comment]
@Guoli-Lyu 用的是rstrip？

**Comment by ShaneTian** [comment]
> 还是有重复词。
> sgns.merge.bigram里面有125个重复词，而且都是无意义的
> 
> ```
> [
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '..................................................................................................',
>        '--------------------------------------------------------------------------------------------------',
>        '..................................................................................................',
>        ...
>        '--------------------------------------------------------------------------------------------------',
>        '**************************************************************************************************',
>        '..................................................................................................',
>        '**************************************************************************************************',
>        '..................................................................................................',
>        '--------------------------------------------------------------------------------------------------',
>        '**************************************************************************************************',
>        '**************************************************************************************************',
>        '..................................................................................................',
>        '..................................................................................................'
> ]
> ```

+1，除了有些词前面的全角空格这种情况之外，还会出现这些重复。我是 `Mixed-large 综合 300d` 中

**Comment by shenshen-hungry** [comment]
@ShaneTian 这些长度太长被截断的词（连续重复很多次的符号），导致看起来一样。这些都是比较特殊的文本，对于使用来说意义不大，用的时候可以删掉。
