### ISSUE TITLE
Vocabulary size和embedding中的词汇量不符

### ISSUE THREAD

**Issue by cai-lw** [Embedding/Chinese-Word-Vectors#2]
我下载了wikipedia语料的word+char模型，用gensim载入之后显示词汇量为352281，但README中的vocabulary size写的是2129K
按我的理解，两者应该是一样的。请问是我的理解有误还是数据有误？

**Comment by shenshen-hungry** [comment]
vocabulary size是用来描述语料的，在训练词向量的时候过滤了低频词，所以vocabulary size会比词向量里面的多。

**Comment by cai-lw** [comment]
@shenshen-hungry 但是这个表格后面有这么一句话

> All words are concerned, including low frequency words.

**Comment by cai-lw** [comment]
顺便我google了一下似乎没有找到你们的论文，请问能发一下论文的投稿版到我的邮箱吗（就是github个人资料上写的邮箱）？因为我打算在我的工作中引用你们的论文。

**Comment by shenshen-hungry** [comment]
> @shenshen-hungry 但是这个表格后面有这么一句话
> 
> All words are concerned, including low frequency words.

这里是说在统计corpus信息的时候是针对整个corpus的，也就是corpus里面所有的词汇都被统计了。在训练词向量的时候，通常做法是去掉低频词，所以词向量的词表要小于corpus的词表。

论文稍后会上传arxiv供引用，需要稍等一下下。
