### ISSUE TITLE
请问是否提供out of vocabulary的词向量

### ISSUE THREAD

**Issue by lujiaying** [Embedding/Chinese-Word-Vectors#23]
一个oov的词，对应词向量里哪个token呢？

**Comment by shenshen-hungry** [comment]
oov你可以用所有词向量的平均，或者根据下游任务随机初始化一个向量之后finetune就可以。

**Comment by rudaoshi** [comment]
难道不是词表里对应  UNKNOWN 的那个向量吗？
训练时你们没有引入 UNK 词？
