### ISSUE TITLE
建议对英文词进行大小写归一化处理

### ISSUE THREAD

**Issue by boringcoder** [Embedding/Chinese-Word-Vectors#25]
如SSH，Ssh，ssh等统一处理为ssh，进一步可以考虑是否进行stemming等等

**Comment by shenshen-hungry** [comment]
我们是参考了Google词向量的策略来进行预处理的。在他们的词向量训练过程中并没有对大小写做处理。
实际上，替换大小写是一个trade-off，比如apple指的是苹果（水果）而Apple指的是苹果（公司），进行替换未必合适。
