### ISSUE TITLE
词向量文件无法load

### ISSUE THREAD

**Issue by zhenghaor10** [Embedding/Chinese-Word-Vectors#29]
试了一个百科预料生成的此向量，用gensim进行load（之所以用load方式，是因为想用gensim做增量学习），gensim.models.Word2Vec.load("sgns.baidubaike.bigram-char") 报错，

![2018-06-25 7 00 08](https://user-images.githubusercontent.com/19257392/41846672-04345e34-78aa-11e8-8189-fc94700b4cc8.png)

**Comment by shenshen-hungry** [comment]
你试试这样：
```
from gensim.models.keyedvectors import KeyedVectors
w2v = KeyedVectors.load_word2vec_format("sgns.baidubaike.bigram-char", binary=False, unicode_errors='ignore')
```

**Comment by zhenghaor10** [comment]
多谢，可以load了。但还有个小问题，比之前word2vec的word embedding文件load消耗的时间明显要长，不知道什么原因。。。

**Comment by shenshen-hungry** [comment]
因为：文件大。。。
