### ISSUE TITLE
关于语料预处理

### ISSUE THREAD

**Issue by helenxu** [Embedding/Chinese-Word-Vectors#31]
感谢作者提供的词向量~想问一下，作者在训练word2vec之前，使用HanLP对语料进行分词，使用的是哪个分词算法呢？HMM还是CRF，这对后续训练的影响大吗？另外，分词时有使用用户自定义词典吗？还有，分词后会做停用词、标点符号的过滤处理吗？非常感谢

**Comment by shenshen-hungry** [comment]
我们用的标准分词，就是StandardTokenizer.segment("");。分词没有使用用户自定义词典。只过滤了<html>之类的标签，没有删除停用词和标点符号。我们的策略类似英文词向量Google News 300d。
