### ISSUE TITLE
can't use word2vec.load()?

### ISSUE THREAD

**Issue by chencjiajy** [Embedding/Chinese-Word-Vectors#34]
I download (People's Daily News 人民日报, Word + Character + Ngram),  and use bzip2 to decompress the file. 
I want to use word2vec.load(), so I rename the file name sgns.renmin.bigram-char to sgns_renmin_bigram_char. 
the error is:
**ValueError:** could not broadcast input array from shape (299) into shape (300)

**Comment by shenshen-hungry** [comment]
The problem is caused by strip(). Since strip() deletes all 'space' at the beginning and the end of a line, if the word is 'space', it will be removed and the first value in the line is the first dimension of the embedding rather than a word. A good python package to load embeddings is Gensim.
