### ISSUE TITLE
Cannot download the pre-trained vector files

### ISSUE THREAD

**Issue by dx80232** [Embedding/Chinese-Word-Vectors#35]
I tried to download context word vectors of Word → Character (1), however, I failed to do that since I cannot register the account of baidu.   Can you upload the dataset to other places such as google drive or dropbox?  Thanks.

**Comment by shenshen-hungry** [comment]
I'm sorry for that. We tried to seek for other network drives, but there is no free drive with enough space to store our embedding files (100+GB), except for Baidu.

**Comment by sahyagiri** [comment]
Can't you use google drive?

**Comment by shenshen-hungry** [comment]
@sahyagiri Embeddings of mixed-large corpus are uploaded to Google Drive.
