### ISSUE TITLE
能把训练词向量的代码开源一下嘛

### ISSUE THREAD

**Issue by qujinqiang** [Embedding/Chinese-Word-Vectors#36]

**Comment by qujinqiang** [comment]
如题，用了下感觉训练的词向量效果不错；但是，我这边的分词标准跟你们的又不一致，没办法直接使用你们的词向量；所以，想问下能不能把训练这块给开源一下

**Comment by shenshen-hungry** [comment]
请参考[toolkits](https://github.com/Embedding/Chinese-Word-Vectors#toolkits)

**Comment by qujinqiang** [comment]
非常感谢
