### ISSUE TITLE
SGNS和PPMI的word+char+ngram的CA8评估效果为什么没有在论文里写出来呢？如果有可以放出来吗？

### ISSUE THREAD

**Issue by PuddingCoder** [Embedding/Chinese-Word-Vectors#38]
你好，首先感谢你们所做的工作，我主观认为context里加入word+char+ngram的效果应该是最好的？但是不知道论文中为什么没有放出来在CA8的评估效果，如果可以放出与其他三种context的对比，可以放在这个issues里面吗？
再次感谢你们的工作~

**Comment by shenshen-hungry** [comment]
由于CA8论文主要集中介绍的是数据集CA8的构建等方面，以及时间的缘故，所以论文当中没有对word+char+ngram进行评测。具体的评测结果写到了另外一篇准备投稿的论文里面，稍后会给出具体的数值。谢谢支持！
