### ISSUE TITLE
大佬，如果想获取某个字符的词嵌入，应该用什么语句啊

### ISSUE THREAD

**Issue by Xshelton** [Embedding/Chinese-Word-Vectors#39]
用这个语句可以看到词嵌入了，
with open('sgns.baidubaike.bigram-char', 'rb') as f:
    for line_b in f:
        line_u = line_b.decode('utf-8')
        print(line_u)
但是比如我想获取“年”这个字的词嵌入，应该怎么写代码呢？
小白 谢谢了。

**Comment by shenshen-hungry** [comment]
每一行包含1+300个元素，第一个元素是词语，后面300个是向量，你想个办法读就可以了。
