### ISSUE TITLE
特殊字符的词向量

### ISSUE THREAD

**Issue by xuenhappy** [Embedding/Chinese-Word-Vectors#41]
词向量里面类似google空白或者回车等特殊字符的"</s>"，embeding没有啊，如果有请问是用什么代表的？

**Comment by shenshen-hungry** [comment]
空格之类的字符都被过滤掉了。我们发现实际上空格回车之类的字符通常情况下并不需要被使用到，特别是他们比“的”、“我”之类的高频词还高频，对绝大多数下游任务几乎没有意义价值。

**Comment by xuenhappy** [comment]
通常之下确实没有必要，有些特殊需求对这些字符反而看中些
