### ISSUE TITLE
Word+Character+Ngram问题

### ISSUE THREAD

**Issue by jeffery-zhougang** [Embedding/Chinese-Word-Vectors#47]
大神，有个问题请教一下。
context feature里面的Word，Word+Ngram，Word+Character，Word+Character+Ngram有什么区别？
词向量是使用window中的词成对的训练跑出来的隐层权重矩阵。
Word+Ngram这种是怎么训练的呢？或者说Ngram模型就是个概率表，这个怎么融合进词向量训练里面的呢？还有+Character也是一样的疑问。
不明白这几个的区别，能否讲解一下，谢谢啦。

**Comment by shenshen-hungry** [comment]
SGNS训练词向量的方式是用中心词预测上下文。
在不同语料训练的词向量那个表格里面，中心词都是单个的词（word），上下文分别是word，word+ngram，word+char，word+char+ngram。
举个例子，句子“我是学生。”，分词结果“我 是 学生 。”，当上下文是word时，“是”预测（我，学生，。），当上下文是word+char的时候“是”预测（我，学生，学，生，。）。
