### ISSUE TITLE
《四库全书》字向量未提供？

### ISSUE THREAD

**Issue by soloice** [Embedding/Chinese-Word-Vectors#5]
您好， readme 里的《四库全书》注释说提供了字向量，因为古汉语多为单字词；但是却没有提供字向量的链接，请问是不对外开放吗？还是稍后会更新 readme 文件？

谢谢~

**Comment by shenshen-hungry** [comment]
稍后会更新的，我们正在训练剩下的那些。

**Comment by soloice** [comment]
好的，谢谢
