### ISSUE TITLE
使用CAD8评估效果不理想

### ISSUE THREAD

**Issue by zxyangyu** [Embedding/Chinese-Word-Vectors#62]
ana_eval_dense.py -v sgns.financial.bigram  -a CA8\semantic.txt
geography add/mul: 0.335/0.358
nature add/mul: 0.111/0.107
history add/mul: 0.0/0.0
people add/mul: 0.088/0.099
Total accuracy (add): 0.243
Total accuracy (mul): 0.257
甚至还有  sgns.financial.word     morphological.txt  条件下
A add/mul: 0.009/0.009
prefix add/mul: 0.086/0.088
AB add/mul: 0.01/0.012
suffix add/mul: 0.075/0.073
Total accuracy (add): 0.049
Total accuracy (mul): 0.05
修改了一处line 36    read_analogy函数中的  open(path,enconding='utf-8')
想知道是什么原因导致的

**Comment by shenshen-hungry** [comment]
CA8是针对通用领域来构建的，但是financial是金融语料训练的，在通用领域的测试上表现如此是正常的。

**Comment by zxyangyu** [comment]
感谢，NLP刚入门
还想请问下，对特定领域词向量评估还有什么值得尝试的方式？
是自己做特定领域的联想推理的数据集进行评估
还是是跳过词向量好坏的纠结，
进一步的进行下游任务实验来看看结果。

**Comment by shenshen-hungry** [comment]
垂直领域的话通常用下游任务更靠谱。
