### ISSUE TITLE
关于《四库全书》的字向量是否少字的问题

### ISSUE THREAD

**Issue by LudoArt** [Embedding/Chinese-Word-Vectors#66]
如在原始语料《史记》中有一字“讬”，在《四库全书》的字向量中却没有找到该字，似乎不止一个字的缺少，不知是我因打开编码的方式出现的问题还是有什么其他的原因，《史记》的编码方式为`gb18030` 而《四库全书》字向量的打开方式为'utf-8'

感谢您的回答

**Comment by shenshen-hungry** [comment]
缺字是正常现象，我们对低频的字进行了过滤。因为那些字即使训练了，词向量也是不准确的，所以对它们没有训练。

**Comment by LudoArt** [comment]
感谢您的回复！谢谢~
