### ISSUE TITLE
请问词向量文件在哪儿

### ISSUE THREAD

**Issue by wangdomg** [Embedding/Chinese-Word-Vectors#68]
您好，请问词向量文件在哪儿呢，没有找到诶，谢谢～

**Comment by shenshen-hungry** [comment]
在首页README里面[Pre-trained Chinese Word Vectors](https://github.com/Embedding/Chinese-Word-Vectors#pre-trained-chinese-word-vectors)。

**Comment by wangdomg** [comment]
好的 多谢啦～
