### ISSUE TITLE
评估命令中的参数问题

### ISSUE THREAD

**Issue by EdQzz** [Embedding/Chinese-Word-Vectors#69]
python ana_eval_sparse.py -v <vector.txt> -a CA8/morphological.txt
<vector.txt> 这个代表的经过分词后的文本，还是原始文本
如果是经过分词的文本，请问分词工具使用了哪一种

**Comment by shenshen-hungry** [comment]
vector.txt是词向量，即：第一位是词，后面是向量的数值。
CA8/morphological.txt是analogy里面的morphological任务。
以上均涉及单独的词，不是文本。
