### ISSUE TITLE
Question about the download links

### ISSUE THREAD

**Issue by imWildCat** [Embedding/Chinese-Word-Vectors#7]
1. Could you please publish a link to all of the Baidu Netdisk files? I wish to download all the model files quickly rather than one by one.

2. Is there any plan to save the model files to other netdisks? For example, Google Drive or Dropbox. It should be very convenient for oversea researchers.

Many thanks for your work!

**Comment by shenshen-hungry** [comment]
After uploading all data, we will release a link to all files.

Considering free space of Google Drive(15GB) and Dropbox(2GB), we chose Baidu Netdisk(1 TB free space) to store files.

**Comment by imWildCat** [comment]
@shenshen-hungry 

Thanks a lot for your prompt response!

Could I upload the model files in this repo on Google Drive with your license/credit? I have an educational Google Drive account of my previous university.

**Comment by bruceyang620727** [comment]
**Right now all the links does not work!**
Or there might be something wrong with the Baidu Netdisk?

**Comment by shenshen-hungry** [comment]
@imWildCat Thanks for your proposal. We're going to discuss if uploading files to Google Drive.

**Comment by shenshen-hungry** [comment]
@bruceyang620727 I tested the links in China, Korea, Japan and the US. But I didn't meet any problems.

**Comment by bruceyang620727** [comment]
Hi Shenshenphungry,

I have tried every links and I got nothing but the response below:

![screenhunter_02 may 16 14 40](https://user-images.githubusercontent.com/8803592/40100664-50263d42-5917-11e8-901e-0dc540b66526.gif)

**Comment by shenshen-hungry** [comment]
@bruceyang620727 I guess the problem may be caused by your location or web browser. Using a VPN or changing browser could help you download the data.

**Comment by bruceyang620727** [comment]
Dear shenshen-hungry,

Ya! I think you are right cause I totally forgot the VPN^^

**Comment by bruceyang620727** [comment]
I felt sorry about these links!
Neither the browser Chrome with VPN nor my cellphone could download the files for each links.
Plus, there is not a response from the web chrome!
However, the response from cellphone is as below:

![img_0474](https://user-images.githubusercontent.com/8803592/40105687-47323826-5926-11e8-8966-774f6a12ffe4.JPG)

**Comment by shenshen-hungry** [comment]
@bruceyang620727 Did all of links return this page?

**Comment by bruceyang620727** [comment]
Yes! all of the links return the same page

**Comment by bruceyang620727** [comment]
Hi shenshen-hungry,

I wonder if there is any good news since yesterday

**Comment by shenshen-hungry** [comment]
@bruceyang620727 I'm so sorry. Yesterday, I tested all links with several VPN from different countries, but found nothing can cause this error. We'll decide if uploading files to Google Drive or other net disk s not in China.

**Comment by bruceyang620727** [comment]
Dear shenshen-hungry,

Grateful to hear the good news and appreciate for your kindly understanding^^

**Comment by SwatiTiwarii** [comment]
Hi shenshen-hungry,
I am also facing difficulty in downloading word2vec files. I am asked to create an account on Baidu app Because i dont have knowledge of chinese, not able to sign up. Not able to register through my indian mobile number. 
![image](https://user-images.githubusercontent.com/46405184/59498995-574f0a80-8e4b-11e9-9aa6-e80cca3522a7.png)

Does some version of models are present on some google drive link, which overseas people can access.

**Comment by shenshen-hungry** [comment]
@SwatiTiwarii This url ([https://passport.baidu.com/v2/?reg&overseas=1](https://passport.baidu.com/v2/?reg&overseas=1)) supports oversea phone number (except for Europe).
![屏幕快照 2019-06-15 下午5 34 08](https://user-images.githubusercontent.com/30199885/59549792-575b2180-8f95-11e9-87f3-e915e56673f8.jpg)
