### ISSUE TITLE
解压缩预训练模型出错

### ISSUE THREAD

**Issue by qdHe** [Embedding/Chinese-Word-Vectors#76]
在mac上用百度网盘下载sgns.wiki.word.bz2后解压缩的时候报错 “bzip2: Data integrity error when decompressing.” 请问可以检查一下数据吗？还是我下载/解压缩的方法有问题？

**Comment by shenshen-hungry** [comment]
可能是由于没下载完整导致的？建议先看下大小是不是和网盘上的一致。

**Comment by qdHe** [comment]
谢谢，重新下载后可以解压缩
