### ISSUE TITLE
Target Word Vectors和Context Word Vectors的含义是什么？

### ISSUE THREAD

**Issue by Weirdo233** [Embedding/Chinese-Word-Vectors#82]
Skip-Gram是通过Target预测Context，是共用的一个词嵌入矩阵，这里把Target和Context的词嵌入分别给出来的含义是什么？

**Comment by shenshen-hungry** [comment]
并不是用的同一个，这点可以参考Mikolov的word2vec代码，C语言的那个官方版本。

**Comment by Weirdo233** [comment]
> 并不是用的同一个，这点可以参考Mikolov的word2vec代码，C语言的那个官方版本。

ok，我去拜读一下，感谢
