### ISSUE TITLE
sparse_small.txt　没有这个文件吗

### ISSUE THREAD

**Issue by lion-han** [Embedding/Chinese-Word-Vectors#97]
sparse_small.txt　没有这个文件吗

**Comment by shenshen-hungry** [comment]
https://github.com/Embedding/Chinese-Word-Vectors/blob/46a7b7d86255b35530beb12f765ecd0b23a86c40/evaluation/ana_eval_sparse.py#L114
没有这个文件，这里是个示例占位用的，运行代码往里面传参数的时候就会覆盖了。
