### ISSUE TITLE
Word Embedding with Baidu and Wikipedia

### ISSUE THREAD

**Issue by EddieYang211** [Embedding/Chinese-Word-Vectors#98]
I was wondering if you can provide another embedding with both Baidu and Wikipedia as training data?

I notice you have a mixed-large large embedding that merges different corpora but it seems Baidu and Wikipedia are more similar to each other than other corpora.

**Comment by shenshen-hungry** [comment]
Since Baidubaike is only worse than Mixed-large embeddings, I don't think it is necessary to train embeddings based on Baidubaike and Wikipedia. 
And if you want to use embedding trained by wiki-like corpus, it is enough to use Baidubaike embeddings.
