### ISSUE TITLE
能不能把词向量放到别的地方？

### ISSUE THREAD

**Issue by marvinxu-free** [Embedding/Chinese-Word-Vectors#99]
百度云限速，现在速度不行，能不能提供一个别的下载方式？

**Comment by shenshen-hungry** [comment]
又免费又不限速同时空间又大的网盘，我也想知道在哪儿。。。

**Comment by marvinxu-free** [comment]
> 又免费又不限速同时空间又大的网盘，我也想知道在哪儿。。。

直接传到github上面

**Comment by shenshen-hungry** [comment]
所有词向量文件加一起上百个G，GitHub传不了那么多，参见[https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota](https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota)。

即使传上来了下载速度更堪忧，百度网盘至少还能通过会员加速，GitHub没有加速方式。
